# Main information
name: Elemental
version: 0.0.1-BETA
main: net.palenquemc.elemental.Elemental

# Complementary information
api-version: '1.20.6'
description: Plugin with elemental features.

loadbefore: [CommandWhitelist]

# Contact information
author: McYoinet
website: https://plugins.palenquemc.net/Elemental

# Commands
commands:
  elemental:
    description: Main command of the plugin. Shows general information about it.

# Permissions
permissions:
  elemental.plugininfo:
    description: Allows the usage of /elemental
    default: op