# Main information
name: Elemental
version: 0.0.1-BETA
main: net.palenquemc.elemental.Elemental

# Complementary information
api-version: '1.20.6'
description: Plugin with elemental features.

loadbefore: [CommandWhitelist]

# Contact information
author: McYoinet
website: https://plugins.palenquemc.net/Elemental

# Commands
commands:
  elemental:
    description: Main command of the plugin. Shows general information about it.
  broadcast:
    description: Broadcasts a message to all players in the server.
    aliases: [bc, announce]
  gamemode:
    description: Set a player's gamemode.
    aliases: [gm, gmode, mode]
  teleport:
    description: Teleports a player to the specified location.
    aliases: [tp, tele, move]
  world:
    description: Teleports a player to the specified world
    aliases: [changeworld, moveworld]

# Permissions
permissions:
  elemental.plugininfo:
    description: Allows the usage of /elemental
    default: op
  elemental.broadcast:
    description: Allows the usage of /broadcast
    default: op
  elemental.gamemode:
    description: Allows the usage of /gamemode
    default: op
    children:
      elemental.gamemode.others: true
  elemental.teleport:
    description: Allows the usage of /teleport and related commands
    default: op
    children:
      elemental.teleport.others: true